[package]
name = "f1-telemetry"
version = "0.1.0"
authors = ["Mathieu Lemay <mathieu.lemay@broadsign.com>"]
edition = "2018"

[lib]
name = "f1_telemetry"

[[bin]]
name = "f1-telemetry-reader"
path = "src/main.rs"

[dependencies]
byteorder = "^1.3.4"
getset = "^0.1.0"
