[package]
name = "f1-telemetry-common"
version = "0.1.0"
description = "Common utilities"
authors = ["Mathieu Lemay <acidrain1@gmail.com>"]
edition = "2021"

[dependencies]
log = "0.4.17"
simplelog = "0.12.0"
time = "0.3.11"
