[package]
name = "f1-telemetry-display"
version = "0.1.0"
authors = ["Mathieu Lemay <acidrain1@gmail.com>"]
edition = "2018"

[dependencies]
f1-telemetry = { path = "../f1-telemetry" }
ncurses = { version = "^5.99.0", features = ["wide"] }
log = "^0.4"
simplelog = "^0.9"
